import test from 'node:test'
import assert from 'node:assert/strict'
import { clearSession, normalizeApiError, normalizePost, normalizeUser, refreshSession } from '../src/api.js'
test('normalizes the backend error contract',()=>{const e=normalizeApiError({error:{code:'validation_failed',message:'请检查标记字段',field_errors:{content:['不能为空']},request_id:'req_1'}},422);assert.equal(e.code,'validation_failed');assert.equal(e.status,422);assert.deepEqual(e.fieldErrors,{content:['不能为空']});assert.equal(e.requestId,'req_1')})
test('uses a safe fallback for malformed errors',()=>{const e=normalizeApiError({},500);assert.equal(e.message,'请求失败，请稍后重试');assert.equal(e.status,500)})
test('adapts the Go post contract for the timeline',()=>{const p=normalizePost({summary:'摘要',like_count:3,comment_count:2,repost_count:1,author:{display_name:'林野',handle:'linye'}});assert.equal(p.content,'摘要');assert.equal(p.author.name,'林野');assert.equal(p.likes,3);assert.equal(p.comments,2);assert.equal(p.reposts,1)})
test('adapts identity display names',()=>{assert.equal(normalizeUser({display_name:'木棉',handle:'mumian'}).name,'木棉')})
test('clears every local session credential together',()=>{const removed=[];global.sessionStorage={removeItem:key=>removed.push(key)};clearSession();assert.deepEqual(removed,['fanbbs_access_token','fanbbs_refresh_token','fanbbs_user']);delete global.sessionStorage})
test('rotates refresh credentials and cached identity together',async()=>{const values=new Map([['fanbbs_refresh_token','old-refresh']]);global.sessionStorage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};global.fetch=async()=>({ok:true,json:async()=>({data:{access_token:'new-access',refresh_token:'new-refresh',user:{handle:'linye',display_name:'林野'}}})});await refreshSession();assert.equal(values.get('fanbbs_access_token'),'new-access');assert.equal(values.get('fanbbs_refresh_token'),'new-refresh');assert.equal(JSON.parse(values.get('fanbbs_user')).name,'林野');delete global.fetch;delete global.sessionStorage})
