import test from 'node:test'
import assert from 'node:assert/strict'
import { api, clearSession, normalizeApiError, normalizePost, normalizeUser, refreshSession, uploadFile } from '../src/api.js'
test('normalizes the backend error contract',()=>{const e=normalizeApiError({error:{code:'validation_failed',message:'请检查标记字段',field_errors:{content:['不能为空']},request_id:'req_1'}},422);assert.equal(e.code,'validation_failed');assert.equal(e.status,422);assert.deepEqual(e.fieldErrors,{content:['不能为空']});assert.equal(e.requestId,'req_1')})
test('uses a safe fallback for malformed errors',()=>{const e=normalizeApiError({},500);assert.equal(e.message,'请求失败，请稍后重试');assert.equal(e.status,500)})
test('adapts the Go post contract for the timeline',()=>{const p=normalizePost({summary:'摘要',like_count:3,comment_count:2,repost_count:1,author:{display_name:'林野',handle:'linye'}});assert.equal(p.content,'摘要');assert.equal(p.author.name,'林野');assert.equal(p.likes,3);assert.equal(p.comments,2);assert.equal(p.reposts,1)})
test('adapts identity display names',()=>{assert.equal(normalizeUser({display_name:'木棉',handle:'mumian'}).name,'木棉')})
test('clears every local session credential together',()=>{const removed=[];global.sessionStorage={removeItem:key=>removed.push(key)};clearSession();assert.deepEqual(removed,['fanbbs_access_token','fanbbs_refresh_token','fanbbs_user']);delete global.sessionStorage})
test('rotates refresh credentials and cached identity together',async()=>{const values=new Map([['fanbbs_refresh_token','old-refresh']]);global.sessionStorage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};global.fetch=async()=>({ok:true,json:async()=>({data:{access_token:'new-access',refresh_token:'new-refresh',user:{handle:'linye',display_name:'林野'}}})});await refreshSession();assert.equal(values.get('fanbbs_access_token'),'new-access');assert.equal(values.get('fanbbs_refresh_token'),'new-refresh');assert.equal(JSON.parse(values.get('fanbbs_user')).name,'林野');delete global.fetch;delete global.sessionStorage})
test('sends the complete create-post contract without discarding metadata',async()=>{const calls=[];global.sessionStorage={getItem:()=> 'access'};global.fetch=async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>({data:{id:'p1',author:{display_name:'作者'},content:'正文'}})}};const input={title:'完整标题',summary:'摘要',content:'正文',kind:'image',category_id:'cat-1',tag_ids:['tag-1'],media_ids:['media-1'],visibility:'followers'};await api.createPost(input);assert.equal(calls[0].url,'/api/v1/posts');assert.equal(calls[0].options.method,'POST');assert.deepEqual(JSON.parse(calls[0].options.body),input);assert.ok(calls[0].options.headers['Idempotency-Key']);delete global.fetch;delete global.sessionStorage})
test('supports parent_id comments and the dedicated replies endpoint',async()=>{const calls=[];global.sessionStorage={getItem:()=> 'access'};global.fetch=async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>({data:{id:'c1',author:{display_name:'作者'},content:'回复',depth:1}})}};await api.comment('post/1','父级回复','comment/1');await api.reply('post/1','comment/1','专用端点回复');assert.equal(calls[0].url,'/api/v1/posts/post%2F1/comments');assert.deepEqual(JSON.parse(calls[0].options.body),{content:'父级回复',parent_id:'comment/1'});assert.equal(calls[1].url,'/api/v1/posts/post%2F1/comments/comment%2F1/replies');assert.deepEqual(JSON.parse(calls[1].options.body),{content:'专用端点回复'});delete global.fetch;delete global.sessionStorage})
test('uses canonical account and repost mutation methods',async()=>{const calls=[];global.sessionStorage={getItem:()=> 'access'};global.fetch=async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>({data:{changed:true}})}};await api.changePassword('old-password','new-password');await api.deactivateAccount();await api.repost('post-1',true);assert.deepEqual(calls.map(c=>[c.url,c.options.method]),[['/api/v1/me/password','PUT'],['/api/v1/me/account','DELETE'],['/api/v1/posts/post-1/reposts','DELETE']]);assert.deepEqual(JSON.parse(calls[0].options.body),{current_password:'old-password',new_password:'new-password'});delete global.fetch;delete global.sessionStorage})
test('uses backend-backed profile privacy, content and cover routes',async()=>{const calls=[];global.sessionStorage={getItem:()=> 'access'};global.fetch=async(url,options={})=>{calls.push({url,options});return {ok:true,json:async()=>({data:[]})}};await api.blocks('block-cursor');await api.categoryFollows('category-cursor');await api.profilePosts('user/1');await api.profileComments('user/1','comment-cursor');await uploadFile(new File(['cover'],'cover.png',{type:'image/png'}),{cover:true,altText:'主页封面'});assert.deepEqual(calls.slice(0,4).map(call=>call.url),['/api/v1/me/blocks?limit=30&cursor=block-cursor','/api/v1/me/category-follows?limit=30&cursor=category-cursor','/api/v1/users/user%2F1/posts?limit=20','/api/v1/users/user%2F1/comments?limit=20&cursor=comment-cursor']);assert.equal(calls[4].url,'/api/v1/me/cover');assert.equal(calls[4].options.method,'PUT');delete global.fetch;delete global.sessionStorage})
